### ISSUE TITLE
[Proposal] Theme Alias

### ISSUE THREAD

**Issue by vinicius33** [foodora/logistics-cardinal-ui#105]
As discussed before, in order to improve semantics and maintenance at the component level we have to come up with a solution to export a new object for each Theme respectively. My initial suggestion would be something like this:

```javascript
const aliases = {
	colors: {
		primary: primary.primary100,
		secondary: blues.blue200,
		warning: yellows.yello300,
		danger: reds.red100,
		link: blues.blue300,
		...
	},
	fontSize: {
		xs: fontSize.bit,
		sm: '',
		md: '',
		lg: '',
		xl: ''
	}
}
```

By creating something like this we can always grow without any concerns if our components will have any color collision whatsoever.

bootstrap does something similar: https://github.com/twbs/bootstrap/blob/v4-dev/scss/_variables.scss

**Comment by divyanshu-rawat** [comment]
@vinicius33 I would like to take this, Please give me more insights on this.

**Comment by divyanshu-rawat** [comment]
@vinicius33 kindly, let me know if you want to work on this.

**Comment by vinicius33** [comment]
Hey, @divyanshu-rawat extremely sorry for the late reply. Thanks for your proactivity. Currently, this issue has already been solved and we're focusing only on new components. Nonetheless, contributions are always welcome :)
